export const CREDENTIAL_TEST_CONSTANTS = {
  MOCK_DESCRIPTOR_IDS: {
    STATE_ABBREVIATION: 1,
    CREDENTIAL_TYPE: 1,
    CREDENTIAL_FIELD: 1,
    TEACHING_CREDENTIAL: 1,
    TEACHING_CREDENTIAL_BASIS: 1,
  },
  MOCK_QUERY_OPTIONS: {
    limit: 10,
    offset: 0,
  },
  MOCK_IF_MATCH_HEADER: '"2024-01-01T00:00:00.000Z"',
} as const;
